# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='user_id',
        ),
    ]
